services:
  points-api:
    build:
      context: ./points-handler
      args:
        JAR: ./target/*.jar
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/purchase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  kafka-consumer:
    build:
      context: ./kafka-message-handler
      args:
        JAR: ./target/*.jar
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/purchase
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_SECURITY_PROTOCOL: PLAINTEXT
      SPRING_KAFKA_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS:
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: purchase
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql"

  dummy-sales-log:
    image: ghcr.io/yo1000/dummy-sales-log:latest
    ports:
      - "8081:8080"
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      SPRING_KAFKA_TEMPLATE_DEFAULTTOPIC: purchases
      APP_THREAD_NOISESPERSEC: 500

  kafka:
    image: apache/kafka-native
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=docker-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "18081:8080"
    depends_on:
      - kafka

#  nginx:
#    build:
#      context: ./customer-portal
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"  # Nginxがホストするポート
#    volumes:
#      - ./customer-portal/build:/usr/share/nginx/html  # Nginxのデフォルトのhtmlディレクトリにマウント
#    depends_on:
#      - points-api
